stages:
  - Sonar
  - End

variables:
  #  GRADLE_EXT_CMD:
  SONAR_PROJECTKEY: mservice-mms
  SONAR_PROJECTNAME: mservice-mms
  SONAR_SOURCES: java
  SONAR_JAVA_BINARIES: build/classes
  SONAR_JAVA_SOURCE: "1.8"

sonar_preview:
  stage: Sonar
  script:
    - /app/scripts/gitlab-ci-scripts/show_env.sh
    - /app/scripts/gitlab-ci-scripts/build_with_gradle.sh
    - /app/scripts/gitlab-ci-scripts/sonar_incremental.sh
  only:
    refs:
      - merge_requests
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"
  tags:
    - test

end:
  stage: End
  script:
    - echo end
  tags:
    - test