stages:
  - Sonar
  - End

sonar_preview:
  stage: Sonar
  script:
    - sed -i "s,COSMIC_LIBS_BASE_DIR=.*,COSMIC_LIBS_BASE_DIR=/app/cosmic/libs/,g" ./gradle.properties
    - /app/gradle/bin/gradle clean --build-cache copytolib
    - /app/sonar-scanner/bin/sonar-scanner -Dsonar.qualitygate.wait=true -Dsonar.projectKey=mservice-mms -Dsonar.projectName=mservice-mms -Dsonar.java.source=1.8 -Dsonar.sources=java -Dsonar.java.binaries=build/classes -Dsonar.host.url=http://it-sonar.aosom.com
  only:
    refs:
      - merge_requests
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"
  tags:
    - test

end:
  stage: End
  script:
    - echo end
  tags:
    - test